### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
A.
The typo is actually in "signficands" under About, where I can't fix.

B.
At QD.jl:
```
[AccurateArithmetic] is based on similar ideas, but provides an implementation as functions and not as a type.

[ErrorfreeArithmetic] is based on similar ideas, but provides an implementation as functions and not as a type.
```

I wanted to recommend your package, remembered the former (and the paper seems interesting), and with the description there the same, maybe should point to both. I'm not sure if there's any best recommended (error-free) package to point to, or if people need just more precision. QD (and DecFP) and https://github.com/JuliaMath/DoubleFloats.jl also options. I just know you're the main guy to trust.

**Comment by JeffreySarnoff** [comment]
Thank you. Merging this, will fix typo, add links.

**Comment by JeffreySarnoff** [comment]
@PallHaraldsson where exactly is that typo (which file in the tree? at what line?)

**Comment by PallHaraldsson** [comment]
It's on the main page to the right:

About

Calculate with error-free, faithful, and compensated transforms and extended signficands.

**Pull request merged**
